name: Blogs
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://news.google.com/rss/search?q=artificial-intelligence+when:24h&hl=en-US&gl=US&ceid=US:en"
          max_post_count: "6"
          commit_message: "📝 Latest Google News"
          committer_username: "mehedination"
          committer_email: "137965021+mehedination@users.noreply.github.com"
